FROM node:20-alpine AS build

WORKDIR /app

# Define argumentos de build
ARG DB_TYPE
ARG DB_USER
ARG DB_HOST
ARG DB_NAME
ARG DB_PASSWORD
ARG DB_PORT
ARG TZ
ARG AWS_REGION
ARG ORDER_PRODUCT_CREATE_QUEUE
ARG ORDER_PRODUCT_CREATE_ACCEPT_QUEUE
ARG ORDER_PRODUCT_DELETE_QUEUE
ARG ORDER_PRODUCT_DELETE_ACCEPT_QUEUE
ARG ORDER_PRODUCT_UPDATE_QUEUE
ARG ORDER_PRODUCT_UPDATE_ACCEPT_QUEUE
ARG COOK_ORDER_CREATE_QUEUE
ARG ORDER_STATUS_UPDATE_QUEUE
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ENDPOINT
ARG AWS_URL

# Define variáveis de ambiente usando os argumentos recebidos
ENV DB_TYPE=$DB_TYPE \
    DB_USER=$DB_USER \
    DB_HOST=$DB_HOST \
    DB_NAME=$DB_NAME \
    DB_PASSWORD=$DB_PASSWORD \
    DB_PORT=$DB_PORT \
    TZ=$TZ \
    AWS_REGION=$AWS_REGION \
    ORDER_PRODUCT_CREATE_QUEUE=$ORDER_PRODUCT_CREATE_QUEUE \
    ORDER_PRODUCT_CREATE_ACCEPT_QUEUE=$ORDER_PRODUCT_CREATE_ACCEPT_QUEUE \
    ORDER_PRODUCT_DELETE_QUEUE=$ORDER_PRODUCT_DELETE_QUEUE \
    ORDER_PRODUCT_DELETE_ACCEPT_QUEUE=$ORDER_PRODUCT_DELETE_ACCEPT_QUEUE \
    ORDER_PRODUCT_UPDATE_QUEUE=$ORDER_PRODUCT_UPDATE_QUEUE \
    ORDER_PRODUCT_UPDATE_ACCEPT_QUEUE=$ORDER_PRODUCT_UPDATE_ACCEPT_QUEUE \
    COOK_ORDER_CREATE_QUEUE=$COOK_ORDER_CREATE_QUEUE \
    ORDER_STATUS_UPDATE_QUEUE=$ORDER_STATUS_UPDATE_QUEUE \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_ENDPOINT=$AWS_ENDPOINT \
    AWS_URL=$AWS_URL

COPY package.json package-lock.json ./

RUN npm ci --only=production

COPY . .

FROM node:20-alpine

WORKDIR /app

COPY --from=build /app /app

EXPOSE 9100

CMD ["node", "dist/main.js"]
