CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS COOK_ORDER (
    ID UUID PRIMARY KEY,
    SEQUENCE SERIAL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);
