CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE ORDER_PRODUCT (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ORDER_ID UUID REFERENCES COOK_ORDER(id),
    PRODUCT_ID UUID REFERENCES PRODUCT(id),
    CUSTOMIZATION VARCHAR(100),
    CREATED_AT TIMESTAMP
);
