name: Flyway Cook Migrations run

on:
  workflow_dispatch: # Permite execução manual

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Flyway
        run: |
          curl -L "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.21.0/flyway-commandline-9.21.0-linux-x64.tar.gz" | tar xz
          sudo ln -s "$(pwd)/flyway-9.21.0/flyway" /usr/local/bin/flyway

      - name: Criar arquivo de configuração do Flyway
        run: |
          echo "flyway.url=jdbc:postgresql://${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}" > flyway.conf
          echo "flyway.user=${{ secrets.DB_USER }}" >> flyway.conf
          echo "flyway.password=${{ secrets.DB_PASSWORD }}" >> flyway.conf
          echo "flyway.schemas=public" >> flyway.conf
          echo "flyway.locations=filesystem:resources/db/migration" >> flyway.conf

      - name: Rodar Migrations do Flyway
        run: flyway migrate
